#!/bin/bash -l
#
#PBS -N largeComponent
#PBS -A UQ-SCI-SMP
#PBS -l nodes=1:ppn=1:intel
#PBS -l vmem=10GB,mem=10GB
#PBS -l walltime=4:00:00
#PBS -v SCENARIO_INDEX
#PBS -S /bin/bash
#PBS -d /home/uqrshah/Software/largeComponent/Simulations
R CMD BATCH --no-restore --no-save simulation.R simulation.Rout.$SCENARIO_INDEX

